---
output:
  pdf_document: default
  html_document: default
---

Visualization

```{r}
library(readxl)
data0 <- read_excel("Video_Games_Sales_as_at_22_Dec_2016.xlsx")
#View(data0)                                                                    
```

```{r}
#install.packages("ggplot2")
library(ggplot2)
```

```{r}
str(data0)
```

```{r}
ggplot(data0,aes(NA_Sales,Year_of_Release))+geom_line(color="blue")+labs(title="Sales in North America ",x="Sales(millions)",y="Released Year")
```
```{r}
ggplot(data0,aes(EU_Sales,Year_of_Release))+geom_line(color="orange")+labs(title="Sales in Europe ",x="Sales(millions)",y="Released Year")
```
```{r}
ggplot(data0,aes(JP_Sales,Year_of_Release))+geom_line(color="brown")+labs(title="Sales in Japen ",x="Sales(millions)",y="Released Year")
```
```{r}
ggplot(data0,aes(Other_Sales,Year_of_Release))+geom_line(color="purple")+labs(title="Sales in Other Regions ",x="Sales(millions)",y="Released Year")
```
```{r}
ggplot(data0,aes(factor(Genre),color=factor(Year_of_Release)))+geom_bar(position="dodge")+scale_x_discrete(expand=c(0, 0))+labs(title="The Number of Genres in Each Year ",x="Genre",y="Released Number")
```
`




------------------------------------------------------------------------------------------------------------------------------------------
LOGISTIC REGRESSION

1) Data Cleaning

Removing Null value roes and converting non-numeric columns to numeric columns
```{r}
vg <- read.csv("Video_Games_Sales.csv",header = TRUE,na.strings = c("", "N/A"))
vg <- na.omit(vg)
vg$User_Count<-as.numeric(as.character(vg$User_Count))
vg$User_Score<-as.numeric(as.character(vg$User_Score))


```

Refining categorical variable
```{r}
vg$Publisher2=0
vg$Publisher2[(vg$Publisher=="Nintendo")|(vg$Publisher=="Activision")|(vg$Publisher=="Sony Computer Entertainment")|(vg$Publisher=="Electronic Arts")|(vg$Publisher=="Take-Two Interactive")|(vg$Publisher=="Ubisoft")]=1
a <- vg[vg$Publisher2==1,]
dt = sort(sample(nrow(a), nrow(a)*0.6))
train<-a[dt,]
test<-a[-dt,]
```

Relevance of the game based on launch year
```{r}
a$year2[a$Year_of_Release<"2010"]=0
a$year2[(a$Year_of_Release=="2010")|(a$Year_of_Release>"2000")]=1
```

Removing dependent variables: 
The Global_sales variable is basically the addition of all the other sales variables
```{r}
vg1 <- a[,c(2,4,5,10,11,13,16,18)]
vg2 <- a[,c(6,7,8,9,10,11,12,13,14)]
vg3 <- a[,c(10,11,12,13,14)]
```

Creating Binary Variable "Hit"
```{r}


vg2$Hit = 0
vg2$Hit[vg2$Global_Sales>=mean(vg2$Global_Sales)]=1

dt1 = sort(sample(nrow(vg2), nrow(vg2)*0.6))
train1 <- vg2[dt1,]
test1 <- vg2[-dt1,]

```

Data Visualization
```{r}
library(ggplot2, pos = .Machine$integer.max)
a2 <- data.frame(Global_Sales=a$Global_Sales, Publisher=a$Publisher, Genre=a$Genre, Platform=a$Platform)

ggplot(a2, aes(x=Publisher, y=Global_Sales)) + geom_bar(stat="identity") + ggtitle("Global Sales by Publishers")
ggplot(a2, aes(x=Genre, y=Global_Sales)) + geom_bar(stat="identity") + ggtitle("Global Sales by Genres")
ggplot(a2, aes(x=Global_Sales, y=Platform)) + geom_bar(stat="identity") + ggtitle("Global Sales by Console Types")
```


2)Data Exploration and Feature Selection
```{r}
library(car)
scatterplotMatrix(vg3, main= "Scatter plot Matrix")

```
```{r}
cor(vg2)

cor(vg3)


```
The sale variables are all closely correlated to the Global_Sales variable.


Performing Linear Regression
```{r}
lrm1 <- lm(Global_Sales ~ User_Score, data = vg1)
lrm2 <- lm(Global_Sales ~ Critic_Score, data = vg1)
lrm3 <- lm(Global_Sales ~ User_Score + Critic_Score, data = vg1)

summary(lrm1)
summary(lrm2)
summary(lrm3)


```


CR PLots
```{r}
library(car)
crPlots(lrm1)
crPlots(lrm2)
crPlots(lrm3)

```

Spread Level Plot
```{r}
spreadLevelPlot(lrm1)
spreadLevelPlot(lrm2)
spreadLevelPlot(lrm3)
```


```{r}


anova(lrm1, lrm2, lrm3)
AIC(lrm1, lrm2, lrm3)

```


lrm3 is the better model.




Performing Classification using Logistic Regression
```{r}

logit1 <- glm(Hit ~ Critic_Score + User_Score, data = train1 , family = "binomial")
summary(logit1)
plot(logit1)

```

Predicting on test set
```{r}
library("dplyr")
pred <- predict(logit1, data = test1, type = "response")
summary(pred)
#prob <- ifelse(test1$Global_Sales > mean(test1$Global_Sales), 1, 0 )
prob <- ifelse(test1$Global_Sales > 1, 1, 0 )
table(prob ,test1$Hit)
```


------------------------------------------------------------------------------------------------------------------------------------------
kNN

read data
```{r}
getwd()
data<-read_excel("Video_Games_Sales_as_at_22_Dec_2016.xlsx")
```

data clean(remove NA)
```{r}
library(data.table)
library(dplyr)
data<-data[,1:14]
data<-filter(data,data$Name!="")
data<-filter(data,data$Platform!="")
data<-filter(data,data$Year_of_Release!="")
data<-filter(data,data$Genre!="")
data<-filter(data,data$Publisher!="")
data<-filter(data,data$NA_Sales!="")
data<-filter(data,data$EU_Sales!="")
data<-filter(data,data$JP_Sales!="")
data<-filter(data,data$Other_Sales!="")
data<-filter(data,data$Global_Sales!="")
data<-filter(data,data$Critic_Score!="")
data<-filter(data,data$Critic_Count!="")
data<-filter(data,data$Genre!="")
data<-filter(data,data$User_Count!="")
str(data)
```

encoding the data
```{r}
library(dplyr)
str(data)
knn <- data %>% select(c(2,4,5,10,11,13))
str(knn)
knn$Publisher<-as.integer(factor(knn$Publisher))
```
```{r}
knn$Platform<-as.integer(factor(knn$Platform))
knn$Genre<-as.integer(factor(knn$Genre))
knn$Publisher<-as.integer(factor(knn$Publisher))
knn$Global_Sales<-as.numeric(factor(knn$Global_Sales))
knn$User_Score<-as.numeric(knn$User_Score)
str(knn)
```

Divide data
```{r}
set.seed(200)
train.index <- sample(c(1:dim(knn)[1]),0.8*dim(knn)[1])
knn.train<-as.data.frame(knn[train.index,])
knn.valid<-as.data.frame(knn[-train.index,])
```

schling
```{r}
standardize <- function(x){
  return ((x-mean(x))/sd(x))
}
knn.trainstand<- as.data.frame(lapply(knn.train,standardize))
knn.validstand<- as.data.frame(lapply(knn.valid,standardize))
```

```{r}
library(class)
library(gmodels)
library(e1071)
library(Metrics)
library(kknn)
accuracy.df <- data.frame(k=seq(1,15,1),RMSE=rep(0,15))
knn1 <- knnreg(Global_Sales~., knn.trainstand, k = 1)
knn2 <- knnreg(Global_Sales~., knn.trainstand, k = 2)
knn3 <- knnreg(Global_Sales~., knn.trainstand, k = 3)
knn4 <- knnreg(Global_Sales~., knn.trainstand, k = 4)
knn5 <- knnreg(Global_Sales~., knn.trainstand, k = 5)
knn6 <- knnreg(Global_Sales~., knn.trainstand, k = 6)
knn7 <- knnreg(Global_Sales~., knn.trainstand, k = 7)
knn8 <- knnreg(Global_Sales~., knn.trainstand, k = 8)
knn9 <- knnreg(Global_Sales~., knn.trainstand, k = 9)
knn10 <- knnreg(Global_Sales~., knn.trainstand, k = 10)
```


```{r}
rmse(knn.trainstand$Genre,predict(knn1, knn.trainstand))
rmse(knn.trainstand$Genre,predict(knn2, knn.trainstand))
rmse(knn.trainstand$Genre,predict(knn3, knn.trainstand))
rmse(knn.trainstand$Genre,predict(knn4, knn.trainstand))
rmse(knn.trainstand$Genre,predict(knn5, knn.trainstand))
rmse(knn.trainstand$Genre,predict(knn6, knn.trainstand))
rmse(knn.trainstand$Genre,predict(knn7, knn.trainstand))
rmse(knn.trainstand$Genre,predict(knn8, knn.trainstand))
rmse(knn.trainstand$Genre,predict(knn9, knn.trainstand))
rmse(knn.trainstand$Genre,predict(knn10, knn.trainstand))
```

```{r}
knn10 <- knnreg(Global_Sales~., knn.trainstand, k = 10)
predict3 <- predict(knn10, knn.trainstand)
predict4 <- predict(knn10, knn.validstand)
cor(knn.trainstand$Global_Sales,predict3)
cor(knn.validstand$Global_Sales,predict4)
accuracy(knn.trainstand$Global_Sales,predict3)
accuracy(knn.validstand$Global_Sales,predict4)
```


